#### PP ### / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --name=pool100 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
#### PP + ER FULL ### / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=500 --buffer_bs=2 --keys_agg=random --pool_freq --name=pool100_ER500 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

#### PP + Teacher + ER FULL ### / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_teacher --num_shared_keys_per_pair=2 --replay=ring --buffer_size=500 --buffer_bs=2 --keys_agg=random --pool_freq --name=pool100_teacher_ER500 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=teacher_tune --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
############## Subset
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_teacher --num_shared_keys_per_pair=2 --replay=ring --buffer_size=500 --buffer_bs=2 --keys_agg=random --pool_freq --name=pool100_teacher_ER500_susbset --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --warmup_steps=10 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

#### PP + FIXED ASSIGNMENT on ALL data #### / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_lr=100 --name=pool200_fixed_selection_plr100 --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_lr=10 --name=pool200_fixed_selection_plr10 --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_lr=1 --name=pool200_fixed_selection_plr1 --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# #### Shared prompts and Replay / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_lr=100 --name=shpt --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_lr=100 --name=shpt_ER500 --replay=ring --buffer_size=500 --buffer_bs=2 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

#### TSPT / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=TSPT --prompt_method=tspt --prompt_lr=100 --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=final_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

####  NSL + Replay / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=500 --add_task_prefix --add_lang_ids --bleu_samples=5000 --log_steps=10 --data_num=-1 --warmup_steps=500 --save_last_checkpoints --always_save_model --project_name=final_1 --name=nsl_ER500 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

### TSPT + PP ##### / Tested
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.9 --task_specific_ratio=0.9 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.8 --task_specific_ratio=0.8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.7 --task_specific_ratio=0.7 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.6 --task_specific_ratio=0.6 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.9_ER500 --task_specific_ratio=0.9 --replay=ring --buffer_size=500 --buffer_bs=2 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.8_ER500 --task_specific_ratio=0.8 --replay=ring --buffer_size=500 --buffer_bs=2 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.7_ER500 --task_specific_ratio=0.7 --replay=ring --buffer_size=500 --buffer_bs=2 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.6_ER500 --task_specific_ratio=0.6 --replay=ring --buffer_size=500 --buffer_bs=2 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small




##### SUMM #####
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --name=pool160_5k --pool_size=160 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=1000 --warmup_steps=100 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=summ_pool --stream=summarize
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=nsl_ER500 --replay=ring --buffer_size=500 --add_task_prefix --add_lang_ids --bleu_samples=5000 --log_steps=10 --data_num=-1 --warmup_steps=100 --train_batch_size=8 --eval_batch_size=32 --save_last_checkpoints --always_save_model --project_name=summ_pool --stream=summarize
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=TSPT --prompt_method=tspt --prompt_lr=100 --num_prompts_per_task=100 --train_only_prompts --bleu_samples=-1 --warmup_steps=100 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=summ_pool --stream=summarize

