##### TRY INITIALIZATIONS #####

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=data --prompt_key_init=data --name=pool_data_data --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=vocab --prompt_key_init=uniform --name=pool_voc_uni --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=vocab --prompt_key_init=xavier --name=pool_voc_xav --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=xavier --prompt_key_init=xavier --name=pool_xav_xav --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=xavier --prompt_key_init=uniform --name=pool_xav_uni --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=uniform --prompt_key_init=xavier --name=pool_uni_xav --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_init=uniform --prompt_key_init=uniform --name=pool_uni_uni --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=10000 --save_last_checkpoints --always_save_model --project_name=init10k --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# #### Shared prompts and Replay
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt_replay100 --replay=ring --buffer_size=100 --buffer_bs=2 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt_replay500 --replay=ring --buffer_size=500 --buffer_bs=2 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt_replay1000 --replay=ring --buffer_size=1000 --buffer_bs=8 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt_replay2000 --replay=ring --buffer_size=2000 --buffer_bs=8 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=shpt_replay5000 --replay=ring --buffer_size=5000 --buffer_bs=8 --prompt_method=shpt --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=shpt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ### Pooling Debugging - nokeys, bigger_pool, freq_norm, batching
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool60_data_keyaggrandom --pool_size=60 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --batched_prompts --pool_freq --prompt_init=data --prompt_key_init=data --name=pool60_data_batched_keyaggrandom --pool_size=60 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool60_data_freqnorm_keyaggrandom --pool_size=60 --prompt_method=pool --num_prompts_per_task=20 --pool_freq_norm --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool60_data_nokeys_keyaggrandom --no_keys --pool_size=60 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool300_data_keyaggrandom --pool_size=300 --prompt_method=pool --num_pool_prompt_tokens=1 --num_prompts_per_task=100 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --batched_prompts --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_batched_keyaggrandom --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_freqnorm_keyaggrandom --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --pool_freq_norm --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --no_keys --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_nokeys_keyaggrandom --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool500_data_keyaggrandom --pool_size=500 --prompt_method=pool --num_pool_prompt_tokens=1 --num_prompts_per_task=100 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


#### PP + FIXED ASSIGNMENT on ALL data ####
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_init=data --prompt_key_init=data --name=pool200_data_fixed_selection --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=all_data --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_init=data --prompt_key_init=data --name=pool500_data_fixed_selection --pool_size=500 --prompt_method=pool_fixed --num_pool_prompt_tokens=1 --num_prompts_per_task=100 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=all_data --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_lr=100 --prompt_init=data --prompt_key_init=data --name=pool200_data_fixed_selection_plr100 --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=all_data --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_lr=10 --prompt_init=data --prompt_key_init=data --name=pool200_data_fixed_selection_plr10 --pool_size=200 --prompt_method=pool_fixed --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=all_data --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ### PP + Cluster Center Loss ####
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=0.0001 --prompt_loss_type=clus_center --name=pool500_cenloss0.0001 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=0.001 --prompt_loss_type=clus_center --name=pool500_cenloss0.001 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=0.01 --prompt_loss_type=clus_center --name=pool500_cenloss0.01 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=0.1 --prompt_loss_type=clus_center --name=pool500_cenloss0.1 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=1 --prompt_loss_type=clus_center --name=pool500_cenloss1 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=10 --prompt_loss_type=clus_center --name=pool500_cenloss10 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --center_lambda=100 --prompt_loss_type=clus_center --name=pool500_cenloss100 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=cen_loss --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


### TSPT + PP #####
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.9 --task_specific_ratio=0.9 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.8 --task_specific_ratio=0.8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.7 --task_specific_ratio=0.7 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.6 --task_specific_ratio=0.6 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.8_er --task_specific_ratio=0.8 --replay=ring --buffer_size=5000 --buffer_bs=8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.8_er --task_specific_ratio=0.8 --replay=ring --buffer_size=5000 --buffer_bs=8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.7_er --task_specific_ratio=0.7 --replay=ring --buffer_size=5000 --buffer_bs=8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --name=all_tsr0.6_er --task_specific_ratio=0.6 --replay=ring --buffer_size=5000 --buffer_bs=8 --pool_freq --pool_size=100 --prompt_method=pool --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --data_num=-1 --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --save_last_checkpoints --always_save_model --project_name=tspt_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small




# #### PP + ER #####
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=500 --buffer_bs=2 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=5000 --save_last_checkpoints --always_save_model --project_name=init5k_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

#### PP + ER FULL ###
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=5000 --buffer_bs=8 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=5000 --warmup_steps=500 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=pool_er --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=100 --buffer_bs=2 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=pool_er --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=500 --buffer_bs=2 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=pool_er --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=1000 --buffer_bs=8 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=pool_er --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=2000 --buffer_bs=8 --keys_agg=random --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_ER --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=-1 --save_last_checkpoints --always_save_model --project_name=pool_er --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


source sh/runs4.sh

# # #### Effect of key Prompt and Keys LR ###
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=100 --query_key_lr=0.1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr100_qlr0.1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=10 --query_key_lr=0.1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr10_qlr0.1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=1 --query_key_lr=0.1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr1_qlr0.1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=100 --query_key_lr=1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr100_qlr1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=10 --query_key_lr=1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr10_qlr1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=1 --query_key_lr=1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_qlr1_qlr1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small



# #### Effect of key LR ###
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=0.01 --query_key_lr=0.01 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_qlr0.01 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=0.1 --query_key_lr=0.1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_qlr0.1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=1 --query_key_lr=1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_qlr1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=10 --query_key_lr=10 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_qlr10 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr --stream=concode_none,translate_java-cs,summarize_ruby
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --prompt_lr=0.001 --query_key_lr=0.001 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_qlr0.001 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=16 --eval_batch_size=64 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_lr --stream=concode_none,translate_java-cs,summarize_ruby


# #### Effect of key Loss weight ###
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=0.0001 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam0.0001 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=0.001 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam0.001 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=0.01 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam0.01 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=0.1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam0.1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=1 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam1 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --keys_agg=random --pool_lambda=10 --pool_freq --prompt_init=data --prompt_key_init=data --name=pool100_data_keyaggrandom_plam10 --pool_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=50 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=2000 --save_last_checkpoints --always_save_model --project_name=tune_plam --stream=concode_none,translate_java-cs,summarize_ruby



# #### MEAN POOLING ###
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --io_queries --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=io_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --io_queries --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=io_pool_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --io_queries --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=io_pool_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_all --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_all_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_all_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq_norm --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_freq --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_freq_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --query_pooling_mode=mean --pool_freq_norm --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=mean_pooling --name=pool_freq_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small





# ### TSPT ###
# CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python cont_gen.py --prompt_init=uniform --query_pooling_mode=mean --prompt_lr=100 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tspt --name=tspt_mean_uniform --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python cont_gen.py --prompt_init=vocab --query_pooling_mode=mean --prompt_lr=100 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tspt --name=tspt_mean_vocab --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python cont_gen.py --prompt_init=uniform --query_pooling_mode=sos --prompt_lr=100 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tspt --name=tspt_sos_uniform --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python cont_gen.py --prompt_init=vocab --query_pooling_mode=sos --prompt_lr=100 --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tspt --name=tspt_sos_vocab --stream=concode_none,translate_java-cs,summarize_ruby,refine_small



# ## COSINE SIMILARITY of POOL + Proj + Replay #######
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --name=pool~try=0 --eval_batch_size=80 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq  --eval_batch_size=80  --name=pool_shared_proj~try=0 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq  --eval_batch_size=80  --name=pool_sep_proj~try=0 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_replay~try=0 --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_shared_proj_replay~try=0 --pool_freq --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_sep_proj_replay~try=0 --pool_freq --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=allparams_pool_replay~try=0 --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=allparams_pool_shared_proj_replay~try=0 --pool_freq --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=allparams_pool_sep_proj_replay~try=0 --pool_freq --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ## COSINE SIMILARITY of POOL + Proj + freq_norm + Replay #######
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool~try=0 --pool_freq_norm --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_shared_proj~try=0 --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_sep_proj~try=0 --pool_freq_norm --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ## COSINE SIMILARITY of POOL + Proj + IO_query + Replay #######
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool~try=1 --io_queries --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_shared_proj~try=0 --io_queries --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --compute_avg_sim --pool_freq --eval_batch_size=80 --name=pool_sep_proj~try=0 --io_queries --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small



# ##### POOL + Proj + Replay ####
# # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=100 --prompt_method=pool --separate_projection --train_only_prompts --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20  --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --warmup_steps=10 --save_last_checkpoints --always_save_model --project_name=task_exp2 --name=CSTR_tuned_prompt_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --num_prompts_per_task=100 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=tspt --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --num_prompts_per_task=100 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=tspt_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=allparams_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=allparams_pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_replay --name=allparams_pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ##### POOL + Proj + freq_norm + Replay ####
# # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=100 --prompt_method=pool --separate_projection --train_only_prompts --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20  --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --warmup_steps=10 --save_last_checkpoints --always_save_model --project_name=task_exp2 --name=CSTR_tuned_prompt_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=allparams_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=allparams_pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --pool_freq_norm --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_freq_replay --name=allparams_pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ##### POOL + Proj + IO_query + Replay ####
# # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --replay=ring --buffer_size=100 --prompt_method=pool --separate_projection --train_only_prompts --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20  --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=-1 --warmup_steps=10 --save_last_checkpoints --always_save_model --project_name=task_exp2 --name=CSTR_tuned_prompt_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool_shared_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool_sep_proj --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=allparams_pool_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=allparams_pool_shared_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --io_queries --replay=ring --buffer_size=100 --prompt_projection --separate_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=debug_pool_io_replay --name=allparams_pool_sep_proj_replay --stream=concode_none,translate_java-cs,summarize_ruby,refine_small



# ### POOL TUNE LAMBDA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=0.1 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_0.1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=0.3 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_0.3 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=0.5 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_0.5 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=0.7 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_0.7 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=1 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_1 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --prompt_projection --separate_projection --pool_lambda=2 --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --num_prompts_per_task=20 --train_only_prompts --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --train_batch_size=8 --eval_batch_size=32 --log_steps=10 --data_num=1000 --save_last_checkpoints --always_save_model --project_name=tune_pool_lambda --name=lambda_2 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# source sh/runs3.sh
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool_IOQ --name=1000_IOQ_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small






# ### Pooling Experiments
# ## MTL 1000
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python run_multi_gen.py --task=all_tasks --log_steps=100 --num_saves=5 --max_source_length=-1 --max_target_length=-1 --data_num=1000 --warmup_steps=1000 --learning_rate=5e-5 --patience=-1 --save_last_checkpoints --always_save_model --train_batch_size=16 --eval_batch_size=100 --name=1000_multitask_tasks --project_name=debug_pool1

# ### test input output to query
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool_IOQ --name=1000_IOQ_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --separate_projection --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool_IOQ --name=1000_IOQ_sep_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool_IOQ --name=1000_IOQ --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# #p31, p32, p33, p34
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# # CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --prompt_projection --projection_hid_dim=2048 --projection_out_dim=2048 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_proj_expansion --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_fnorm_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --pool_freq_norm --prompt_projection --projection_hid_dim=2048 --projection_out_dim=2048 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_fnorm_proj_expansion --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# # p4
# CUDA_VISIBLE_DEVICES=0,1,2,3 python cont_gen.py --train_batch_size=16 --eval_batch_size=64 --prompt_method=pool --separate_projection --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_sep_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=4,5,6,7 python cont_gen.py --train_batch_size=16 --eval_batch_size=64 --prompt_method=pool --separate_projection --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_fnorm_sep_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --separate_projection --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=80 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_pool80_fnorm_sep_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --separate_projection --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --pool_lambda=0.5 --pool_size=120 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_pool120_fnorm_sep_proj_contract --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --separate_projection --pool_freq_norm --prompt_projection --projection_hid_dim=2048 --projection_out_dim=2048 --pool_lambda=0.5 --pool_size=120 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_pool120_fnorm_sep_proj_expansion --stream=concode_none,translate_java-cs,summarize_ruby,refine_small




# CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=16 --eval_batch_size=64 --prompt_method=pool --separate_projection --prompt_projection --projection_hid_dim=2048 --projection_out_dim=2048 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_sep_proj_expansion --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=16 --eval_batch_size=64 --prompt_method=pool --separate_projection --pool_freq_norm --prompt_projection --projection_hid_dim=2048 --projection_out_dim=2048 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --bleu_samples=100 --num_train_epochs=30 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=1000_fnorm_sep_proj_expansion --stream=concode_none,translate_java-cs,summarize_ruby,refine_small




# CUDA_VISIBLE_DEVICES=0,1,2,3 python cont_gen.py --train_batch_size=16 --eval_batch_size=100 --prompt_method=pool --pool_freq_norm --pool_lambda=0.5 --pool_size=80 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=500 --bleu_samples=50 --num_train_epochs=15 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=500_fnorm_pool80 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=4,5,6,7 python cont_gen.py --train_batch_size=16 --eval_batch_size=100 --prompt_method=pool --pool_freq_norm --pool_lambda=0.5 --pool_size=100 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=500 --bleu_samples=50 --num_train_epochs=15 --patience=100 --warmup_steps=0 --save_last_checkpoints --always_save_model --project_name=debug_pool1 --name=500_fnorm_pool100 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ### Compute similarity
# CUDA_VISIBLE_DEVICES=0 python compute_sim.py --eval_batch_size=80 --name=500_fnorm_pool80~try=0 --prompt_method=pool --num_prompts_per_task=20 --prompt_init=vocab --num_pool_prompt_tokens=5 --pool_size=80 --pool_freq --compute_avg_sim --data_num=500 --project_name=debug_pool  --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# ### PROMPT POOL: Cosine Similarity ###
# ### Works only on a single gpu. Inplace concatenation doesn't works hence DP losses the computed values.
# CUDA_VISIBLE_DEVICES=0 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --compute_avg_sim --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --num_train_epochs=1 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=query_sim --stream=concode_none,translate_java-cs,summarize_ruby,refine_small --no_eval --no_eval_bleu --no_eval_all --no_test
# CUDA_VISIBLE_DEVICES=1 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --compute_avg_sim --prompt_method=pool --prompt_projection --projection_out_dim=64 --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --num_train_epochs=1 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=query_project_sim --stream=concode_none,translate_java-cs,summarize_ruby,refine_small --no_eval --no_eval_bleu --no_eval_all --no_test


# ### PROMPT POOL: Prompt frequency ###
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=freq_dist --stream=concode_none,translate_java-cs,summarize_ruby,refine_small --no_eval_all --no_test
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq_norm --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=1000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=1k_freq_dist_nonorn --stream=concode_none,translate_java-cs,summarize_ruby,refine_small --no_eval_all --no_test



# ### Debugging Prompt Pool ###
# CUDA_VISIBLE_DEVICES=0,1,2,3 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool_project_down --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --prompt_projection --projection_hid_dim=1024 --projection_out_dim=1024 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool_project_up --stream=concode_none,translate_java-cs,summarize_ruby,refine_small

# CUDA_VISIBLE_DEVICES=4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq_norm --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool_freq --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq_norm --prompt_projection --projection_hid_dim=512 --projection_out_dim=64 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool_freq_project_down --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq_norm --prompt_projection --projection_hid_dim=1024 --projection_out_dim=1024 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool_freq_project_up --stream=concode_none,translate_java-cs,summarize_ruby,refine_small


# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --pool_freq_norm --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=2000 --warmup_steps=50 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=CSTR_pool --stream=concode_none,translate_java-cs,summarize_ruby,refine_small



# ######## TUNING PROMPT POOLING ###########
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --bleu_samples=500 --num_train_epochs=10 --log_steps=10 --data_num=5000 --warmup_steps=1 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=naive --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --bleu_samples=500 --num_train_epochs=10 --prompt_method=pool --pool_lambda=0.5 --pool_size=60 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=5000 --warmup_steps=1 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=pool_60_20_5 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --bleu_samples=500 --num_train_epochs=10 --prompt_method=pool --pool_lambda=0.5 --pool_size=40 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=5000 --warmup_steps=1 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=pool_40_20_5 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --bleu_samples=500 --num_train_epochs=10 --prompt_method=pool --pool_lambda=0.5 --pool_size=80 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=5000 --warmup_steps=1 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=pool_80_20_5 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cont_gen.py --train_batch_size=8 --eval_batch_size=32 --bleu_samples=500 --num_train_epochs=10 --prompt_method=pool --pool_lambda=0.5 --pool_size=100 --num_pool_prompt_tokens=5 --num_prompts_per_task=20 --train_only_prompts --log_steps=10 --data_num=5000 --warmup_steps=1 --save_last_checkpoints --always_save_model --project_name=debug_pool --name=pool_100_20_5 --stream=concode_none,translate_java-cs,summarize_ruby,refine_small





# # kill all processes on gpu XXX
for i in $(sudo lsof /dev/nvidia0 | grep python  | awk '{print $2}' | sort -u); do kill -9 $i; done
